### ISSUE TITLE
Significant refactoring needed so that external contributors can contribute 

### ISSUE THREAD

**Issue by danias** [bitloops/bitloops-language#15]
### Subject of the issue
Significant refactoring needed so that external contributors can contribute

**Comment by ellik95** [comment]
- Move this.props addition in domain methods to AST typescript model
- Move if/else wrapping on domain evaluations to AST typescript model
- Fix rule declaration that is implemented in a hacky way
- Refactor `domainCreateEntityMethod` with `domainCreate` method which is similar (only the constructor changes)

**Comment by Varagos** [comment]
#150 Research whether we should create different types for each element (DTO, struct, Props etc..) in parser, or whether this should be done in the semantic analysis step (intermediate model validation), while keeping one type in the parser.

**Comment by sardounis** [comment]
Create specific classes for:

- Navigating in the model
- Bulding the model

**Comment by sardounis** [comment]
add tests for dependencies (toTarget)
