### ISSUE TITLE
🖥️ [CLI] import path slashes on are not concatenated propertly

### ISSUE THREAD

**Issue by frostedpenguin** [bitloops/bitloops-language#170]
### Expected behaviour
```typescript
import { DomainErrors } from '../domain/errors/index'; 1️⃣ 

import { TodoReadRepoPort } from '../../ports/TodoReadRepoPort'; 2️⃣ 
```

### Actual behaviour
```typescript
import { DomainErrors } from '../domainerrors/index'; 1️⃣ 

import { TodoReadRepoPort } from '....ports/TodoReadRepoPort'; 2️⃣ 
```

### Steps to reproduce
_run_ `bl transpile`
### Your environment
* version of Bitloops Language: _0.1.0_

**Comment by Varagos** [comment]
I believe if the function in `src/target/typescript/utils/findRelativeDiff.ts`  uses the file separator of nodejs.path module instead of `/` this will be fixes

**Comment by Varagos** [comment]
This happens on WIndows only, linked with #157

**Comment by frostedpenguin** [comment]
_fixed with #178_
