### ISSUE TITLE
expression - bl to intermediate ast

### ISSUE THREAD

**Issue by Varagos** [bitloops/bitloops-language#191]
Refactor expression subrules using Trees.

expression
  ~~: Not expression                                             # NotExpression~~
    ~~| OpenParen expression CloseParen                            # ParenthesizedExpression~~
    ~~| expression Dot regularIdentifier                           # MemberDotExpression~~
    ~~| expression methodArguments                                 # MethodCallExpression~~
    ~~| expression Dot GetClass OpenParen CloseParen               # GetClassExpression~~
    ~~| expression Dot ToString OpenParen CloseParen               # ToStringExpression~~
   ~~| expression op=('*' | '/' | '%') expression                 # MultiplicativeExpression~~
    ~~| expression op=('+' | '-') expression                       # AdditiveExpression~~
    ~~| expression op=('<' | '>' | '<=' | '>=') expression         # RelationalExpression~~
        ~~| expression op=('==' | '!=' ) expression                    # EqualityExpression~~
        ~~| expression op=And expression                               # LogicalAndExpression~~
        ~~| expression op=Or expression                                # LogicalOrExpression~~
        ~~| expression op=Xor expression                               # LogicalXorExpression~~
    ~~| expression '=' expression                                  # AssignmentExpression~~
    ~~| literal                                                   # LiteralExpression~~
    ~~| evaluation                                                 # EvaluationExpression~~
    ~~| regularIdentifier                                          # IdentifierExpression~~
    ~~| arrayLiteral                                               # ArrayLiteralExpression~~
    ~~| This                                                       # ThisExpression~~

evaluation
    ~~: isInstanceOf~~
    ~~| builtInClassEvaluation~~
    ~~| errorEvaluation~~
    ~~| dtoEvaluation~~
    ~~| valueObjectEvaluation~~
    ~~| entityEvaluation~~
    | _propsEvaluation (done, but untested, probably needs to be removed)_
    ~~| structEvaluation~~
    ;

**Comment by Varagos** [comment]
Working on evaluationField -> StructEvaluation

**Comment by Varagos** [comment]
From model to target 

expression
: Not expression # NotExpression
| OpenParen expression CloseParen # ParenthesizedExpression
| expression Dot regularIdentifier # MemberDotExpression
| expression methodArguments # MethodCallExpression
| expression Dot GetClass OpenParen CloseParen # GetClassExpression
| expression Dot ToString OpenParen CloseParen # ToStringExpression
| expression op=('*' | '/' | '%') expression # MultiplicativeExpression
| expression op=('+' | '-') expression # AdditiveExpression
| expression op=('<' | '>' | '<=' | '>=') expression # RelationalExpression
| expression op=('==' | '!=' ) expression # EqualityExpression
| expression op=And expression # LogicalAndExpression
| expression op=Or expression # LogicalOrExpression
| expression op=Xor expression # LogicalXorExpression
| expression '=' expression # AssignmentExpression
| literal # LiteralExpression
| evaluation # EvaluationExpression
| regularIdentifier # IdentifierExpression
| arrayLiteral # ArrayLiteralExpression
| This # ThisExpression

evaluation
: isInstanceOf
| builtInClassEvaluation
| errorEvaluation
| dtoEvaluation
| valueObjectEvaluation
| entityEvaluation
| propsEvaluation (done, but untested, probably needs to be removed)
| structEvaluation
;

**Comment by ellik95** [comment]
thisExpression

**Comment by Varagos** [comment]
AssignmentExpression

**Comment by ellik95** [comment]
InstanceOfExpression

**Comment by Varagos** [comment]
MemberDotExpression

**Comment by giorgosnty** [comment]
MemberDotExpression

**Comment by Varagos** [comment]
structEvaluation

**Comment by ellik95** [comment]
entityEvaluation

**Comment by giorgosnty** [comment]
valueObjectEvaluation
