### ISSUE TITLE
Link to list of books missing in Big Idea Vision page in documentation

### ISSUE THREAD

**Issue by aikhan** [bitloops/bitloops-language#356]
**Describe the bug**
Link to list of books missing in Big Idea page

**To Reproduce**
1. Go to https://bitloops.com/docs/bitloops-language/introduction/bigidea#conclusions
2. Scroll down to Conclusions

**Expected behavior**
It should link to the books

**Comment by danias** [comment]
Thanks @aikhan for the feedback! We will update the page with the link soon.

**Comment by danias** [comment]
Here is the link for now: https://docs.google.com/spreadsheets/d/1au69tNRhgD7m2qUXL_HG4vUn9NKK4U2tBsPV0pb_jQA/edit#gid=0
