### ISSUE TITLE
Root is not recognized in front of Entity definition

### ISSUE THREAD

**Issue by danias** [bitloops/bitloops-language#6]
### Subject of the issue
Root is not recognized in front of Entity definition

### Expected behaviour
When Root is placed in front of an Entity declaration then the entity should be considered a Root Entity.

**Comment by frostedpenguin** [comment]
Found t

**Comment by frostedpenguin** [comment]
apperently this
```antlr
rule : LexerRule1 ... rule2;
rule2 : LexerRule2 ...;
```
causes ANTLR to not recognize `rule`. I had to break up the entity component in order to not have this _recursive_ lexer rule problem
